name: "버그 리포트"
description: "오류/예외/오작동을 보고합니다."
title: "[bug] 제목을 요약해 주세요"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        가능하면 짧고 구체적으로 작성해 주세요. 로그와 실행 명령을 포함하면 해결이 빨라집니다.

  - type: textarea
    id: summary
    attributes:
      label: 요약
      description: 무엇이 잘못되었나요?
      placeholder: 예) 특정 쿼리에서 PDF 저장이 실패합니다.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 재현 절차
      description: 문제를 재현하는 최소 단계와 명령을 적어주세요.
      value: |
        1. 가상환경 활성화
        2. 의존성 설치: `pip install -r requirements.txt && python -m playwright install`
        3. 실행: `python google_patents_xhr_downloader.py --query "..." --out ./downloads --max-results 1 --headless --diagnostics`
        4. 결과 관찰
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 기대 동작
      placeholder: 예) 지정 폴더에 PDF가 저장되어야 합니다.

  - type: textarea
    id: actual
    attributes:
      label: 실제 동작/로그
      description: 에러 메시지/스택트레이스/관련 로그를 붙여넣어 주세요.
      render: shell

  - type: textarea
    id: env
    attributes:
      label: 환경 정보
      description: OS, Python/Playwright/httpx/브라우저 채널, 네트워크(프록시 등)
      placeholder: |
        - macOS 14.5, Python 3.11.7
        - Playwright 1.54, Chromium stable
        - requirements.txt와 동일

  - type: checkboxes
    id: checks
    attributes:
      label: 제출 전 확인
      options:
        - label: 최신 `main` 기준으로 재현을 확인했습니다.
          required: true
        - label: `--diagnostics` 사용 시 생성된 민감정보(쿠키/헤더)를 제거했습니다.
          required: true
        - label: 동일/유사 이슈가 없는지 검색했습니다.
          required: false

