name: "기능 제안"
description: "새로운 기능/개선 제안을 등록합니다."
title: "[feat] 제안 제목을 요약해 주세요"
labels: [enhancement]
body:
  - type: textarea
    id: context
    attributes:
      label: 배경/문제 맥락
      description: 어떤 문제를 해결하려 하나요? 사용자 효과는 무엇인가요?
      placeholder: 예) 대량 검색 시 속도 저하와 429 우려가 있습니다.

  - type: textarea
    id: proposal
    attributes:
      label: 제안 내용
      description: 구체적 제안, 인터페이스/옵션 예시, 명령어 예시를 포함해 주세요.
      placeholder: |
        - 옵션 추가: `--concurrency 4`, `--delay 1.5`
        - 처리 흐름: 큐 기반 비동기 다운로드, 결과 리트라이 3회

  - type: textarea
    id: alternatives
    attributes:
      label: 대안/고려 사항
      placeholder: 다른 접근법, 장단점 비교 등을 적어주세요.

  - type: textarea
    id: impact
    attributes:
      label: 영향 범위
      description: 문서/테스트/호환성/운영 영향

  - type: checkboxes
    id: checks
    attributes:
      label: 제출 전 확인
      options:
        - label: 동일/유사 제안이 없는지 확인했습니다.
          required: true
        - label: 보안/약관 준수에 문제가 없음을 검토했습니다.
          required: true

